# results of barter
results:
    # item name, get your from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#enum-constant-summary
    "STICK":
        # chance in %
        chance: 100